services:
  db1:
    image: mirror.gcr.io/postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}
    networks:
      - mylocal
    volumes:
      - ./init1.sql:/docker-entrypoint-initdb.d/init2.sql
      - postgres_data1:/var/lib/postgresql/data
    restart: always

  redis:
    image: mirror.gcr.io/redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - mylocal

  app:
    build: .
    depends_on:
      - db1
    networks:
      - mylocal
    environment:
      DB_HOST: db1
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

volumes:
  postgres_data1:
networks:
  mylocal:
    external: true
    driver: bridge