basePath: /api
definitions:
  models.User:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
  description: This is a sample API for address searching and geocoding using Dadata
    API.
  license:
    name: Apache 2.0
  termsOfService: http://localhost:8080/auth/swagger/index.html
  title: GEO API
  version: "2.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      operationId: SingIn
      parameters:
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
        "400":
          description: Invalid request format
        "500":
          description: Response writer error on write
      summary: SingIn a user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      operationId: SingUp
      parameters:
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Invalid request format
        "500":
          description: Response writer error on write
      summary: Register a user
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
